name: cff

services:
  flood-db:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    shm_size: 1g
    platform: linux/amd64
    environment:
      PGDATA: /pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/pgdata
      - wiyby:/wiyby
    networks:
      cff-internal:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c max_wal_size=2048 # set max_wal_size to prevent warnings when restoring db

volumes: 
  pgdata:
    name: flood-db-pgdata
  wiyby:
    name: flood-db-wiyby

networks:
  cff-internal:
    driver: bridge
